services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startup-backend
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - GO_ENV=production
      - CHROMIUM_FLAGS="--no-sandbox --disable-dev-shm-usage --disable-gpu"
      - CHROMIUM_PATH=/usr/bin/chromium-browser
    volumes:
      - ./pb_data:/app/pb_data
      - ./chrome-data:/tmp/chrome-data
      - /sys/fs/cgroup:/sys/fs/cgroup:rw  # Added cgroup access
    deploy:
      resources:
        limits:
          memory: 512mb
          cpus: '2'
        reservations:
          memory: 256mb
          cpus: '1'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: -1
        hard: -1
