version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startup-backend
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - GO_ENV=production
    volumes:
      - ./pb_data:/app/pb_data
    deploy:
      resources:
        limits:
          memory: 512M
