version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '300M'
        reservations:
          cpus: '0.1'
          memory: '100M'
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - GO_ENV=production
    volumes:
      - ./pb_data:/app/pb_data
