version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    network_mode: "host"  # Use host network
    ports:
      - "8090:8090"  # While not strictly necessary with host network, keeping for documentation
    restart: unless-stopped
    environment:
      - GO_ENV=production
    volumes:
      - ./:/app  # Optional: Mount source code for development

networks:
  default:
    driver: bridge