version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startup-backend
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - GO_ENV=production
    volumes:
      - ./pb_data:/app/pb_data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:    # Added minimum resource reservation
          memory: 256M
    healthcheck:         # Added healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s