version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      - GO_ENV=production
